sudo: false

language: ruby

rvm:
  - ruby-head-clang
  - ruby-head
  - ruby-2.2.3-clang
  - ruby-2.2.3
  - ruby-2.2.2
  - ruby-2.1.7-clang
  - ruby-2.1.7
  - ruby-2.1.6
  - ruby-2.0.0-p647-clang
  - ruby-2.0.0-p647
  - ruby-1.9.3-p551
  - ruby-1.8.7-p374
  - ruby-1.8.7-head
  - ruby-1.8.7
  - mruby-head
  - jruby-9.0.0.0

script:
  - gem --version
